### ISSUE TITLE
Error (socket.error: [Errno 99] Cannot assign requested address)

### ISSUE THREAD

**Issue by daredevil12345** [Eitenne/TopHat#2]
What could be possible solution? Secondly how we can see our victims? same commands as metasploit?

python tophat.py 172.94.65.231 4445
[*] Generating SSL Certificates
[*] Creating Backdoor...
[*] Started reverse handler on 172.94.65.231:4445
[*] Starting the payload handler...
Traceback (most recent call last):
  File "tophat.py", line 194, in <module>
    main()
  File "tophat.py", line 191, in main
    connect()
  File "tophat.py", line 160, in connect
    s.bind((addresser,int(porterica)))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by Eitenne** [comment]
Is that Ip assigned by your network?
