### ISSUE TITLE
move among folders

### ISSUE THREAD

**Issue by ericsuarez** [Eitenne/TopHat#3]
I can't move among folders with cd command.

**Comment by Eitenne** [comment]
Could you be more specific as to what you’re trying to do?

**Comment by ericsuarez** [comment]
Just a simple cd .. or a cd /

**Comment by Eitenne** [comment]
Well it wont because its not a normal shell its not binded to /bin/sh, but you can do stuff like ls Desktop but you will be still in the same directory
